### ISSUE TITLE
Missing reference data

### ISSUE THREAD

**Issue by YuWang-VUMC** [ruppinlab/pathogen-discovery-rules#1]
Hi there,

Thanks for provide this pipeline. I am testing this on our HPC at VUMC. I have made some changes based on our environment. However, it seems like that these reference data mentioned in pathogen-discovery-rules/rules/build-PathSeq-host-files.smk are not provided. Could you provide these, or let know how to prepare them?

Another suggestion or request is that, since there are so many dependencies and tools are needed in the pipeline, it's better to seal everything into a docker/singularity image. This may avoid a lot of installation work, especially about CAMMiQ. Thanks.

Best,

Yu

**Comment by wir963** [comment]
Hey @YuWang-VUMC,

Apologies for the late response. I don't check this repository as often so if you run into any issues, please create an issue at [https://github.com/ruppinlab/CSI-Microbes-identification](https://github.com/ruppinlab/CSI-Microbes-identification), which is really the core library. 

There's a pretty extensive README there that includes details relevant to your request. I think you'll find [the database dependencies section](https://github.com/ruppinlab/CSI-Microbes-identification/tree/master#database-dependencies) particularly relevant for your question. For now, I'd suggest focusing on the PathSeq analysis (rather than CAMMiQ) as that has been better stress-tested. 

Most of the software dependencies are installed via conda (which interacts well with snakemake). Have you had issues with particular installation steps? I'd rather keep the environments for different rules separate and not create a single docker/singularity image for all of the steps but I could certainly look into creating a singularity image for some of them. I'll look into that for CAMMiQ. 

Best, Welles
